Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [161]:
import numpy as np

In [145]:
vec =  np.array([1, 2, 3, 5])

In [148]:
def vecfun(vec, power = vec.size, increasing = False):
  if increasing == False:
      matrix = np.array([x**(power-1-i) for x in vec for i in range(power)]).reshape(vec.size,power)
  elif increasing == True:
      matrix = np.array([x**i for x in vec for i in range(power)]).reshape(vec.size,power)
  
  return matrix


In [155]:
vecfun(vec,6)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [3125,  625,  125,   25,    5,    1]])

In [156]:
np.vander(vec, 6)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [3125,  625,  125,   25,    5,    1]])

In [157]:
vecfun(vec,8, True)

array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [    1,     2,     4,     8,    16,    32,    64,   128],
       [    1,     3,     9,    27,    81,   243,   729,  2187],
       [    1,     5,    25,   125,   625,  3125, 15625, 78125]])

In [158]:
np.vander(vec, 8, True)

array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [    1,     2,     4,     8,    16,    32,    64,   128],
       [    1,     3,     9,    27,    81,   243,   729,  2187],
       [    1,     5,    25,   125,   625,  3125, 15625, 78125]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [215]:
def moving_avg(arr, k=3) :
  return np.array([sum(a[i:i+k])/k for i in range(a.size-k+1)]).round(2)
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_avg(a, 3)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])